notaryserver:
  build: .
  dockerfile: notary-server-Dockerfile
  net: notarynet
  volumes_from:
    - notarymysql
    - notarysigner
  ports:
   - "8080"
   - "4443:4443"
  environment:
    SERVICE_NAME: notary
notarysigner:
  volumes:
   - /dev/bus/usb/003/010:/dev/bus/usb/002/010
   - /var/run/pcscd/pcscd.comm:/var/run/pcscd/pcscd.comm
  build: .
  dockerfile: notary-signer-Dockerfile
  net: notarynet
  volumes_from:
    - notarymysql
notarymysql:
  net: notarynet
  build: ./notarymysql/
  ports:
    - "3306:3306"
